{% set name = "streamlit-keyup" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/streamlit-keyup/streamlit_keyup-0.3.0.tar.gz
  sha256: 8595a14892423243669e5d50e982853ffb7eb201b65952a48676133ab9bbc937

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  # s390x is missing streamlit
  skip: true  # [py<37 or s390x]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - streamlit >=1.2
    - jinja2

test:
  imports:
    - st_keyup
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/blackary/streamlit-keyup
  dev_url: https://github.com/blackary/streamlit-keyup
  doc_url: https://github.com/blackary/streamlit-keyup/blob/main/README.md
  summary: Text input that renders on keyup
  description: |
    If you're collecting text input from your users in your streamlit app, st.text_input
    works well -- as long as you're happy with waiting to get the response when they're finished typing.

    But, what if you want to get the input out, and do something with it every time they type a new key (AKA "on keyup")?
  license: MIT
  license_file: LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - ELundby45
